### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by jomizrahi92** [Donohue/CustomKeyboard#1]
I get an error when i try to build it. http://cl.ly/image/0O0g1s281q1b

**Comment by Donohue** [comment]
I can't reproduce this. I'm on XCode6 Beta2 
![screen shot 2014-06-30 at 2 07 58 pm](https://cloud.githubusercontent.com/assets/1069050/3433652/87286c22-0081-11e4-8864-5f96d0a406f2.png)

**Comment by jomizrahi92** [comment]
I believe this occurs when building for an iOS device, currently when i try to build for the iPhone 4s simulator it builds with no errors. Can this be an Xcode beta issue?

**Comment by jomizrahi92** [comment]
Building for iOS device: ![screen shot 2014-06-30 at 2 29 21 pm](https://cloud.githubusercontent.com/assets/3697849/3433925/7ce990da-0084-11e4-803c-6c9331931bb8.png)

Building for iPhone 4S simulator: 
![screen shot 2014-06-30 at 2 29 50 pm](https://cloud.githubusercontent.com/assets/3697849/3433947/979fe956-0084-11e4-86c7-cecc421e016d.png)

**Comment by Donohue** [comment]
Yup -- looks like a bug in XCode when trying to build against an iOS Device without one plugged in. Probably a good candidate for a bug report.

I tested on simulator and on a device with iOS8 and it works without issue.

**Comment by jomizrahi92** [comment]
Got it to work but archiving doesn't work, ill report a bug. Thanks for your help!
